const languages = {
    'ko': {
        'site_title': '유비홀릭 - 편안함이 채워주는 아름다움',
        'logo_text': '유비홀릭',
        'nav_language': '언어',
        'nav_contact': '연락처',
        'home_title': 'UBHOLIC',
        'home_subtitle': '편안함이 채워주는 아름다움, 속눈썹부터 피부까지',
        'branches_title': '지점 안내',
        'branches_desc': '지점 클릭 시 네이버 지도로 연결됩니다.',
        'branch1_name': '전주본점',
        'branch1_address': '전북 전주시 완산구 소태정3길 16-1 1층',
        'branch1_tel': '0507-1336-1520',
        'branch2_name': '익산점',
        'branch2_address': '전북 익산시 궁동로 96 애플빌딩 2층',
        'branch2_tel': '0507-1390-1189',
        'services_title': '주요 서비스',
        'services_desc': '유비홀릭의 전문적인 뷰티 서비스를 만나보세요.',
        'service1_title': '속눈썹 연장',
        'service1_desc': '자연스럽고 풍성한 속눈썹으로 매력적인 눈매 완성',
        'service2_title': '속눈썹 펌',
        'service2_desc': '뷰러 없이도 아찔한 컬링 유지',
        'service3_title': '속눈썹 복원',
        'service3_desc': '손상된 속눈썹을 건강하고 탄력있게',
        'service4_title': '눈썹 & 아이라인',
        'service4_desc': '또렷하고 자연스러운 반영구 메이크업',
        'service5_title': '왁싱',
        'service5_desc': '매끄럽고 깨끗한 피부를 위한 전문 왁싱',
        'service6_title': '피부관리',
        'service6_desc': '맞춤형 케어로 건강하고 빛나는 피부',
        'location_title': '찾아오는 길 (본점)',
        'location_desc': '유비홀릭 전주본점은 효자동에 위치하고 있습니다.',
        'address_label': '주소:',
        'main_branch_address_text': '전북 전주시 완산구 소태정3길 16-1 1층',
        'contact_title': '연락처',
        'contact_desc': '궁금한 점이 있으시면 언제든지 문의해 주세요.',
        'rep_label': '대표:',
        'rep_name_text': '최유비 (Choi Yubi)',
        'phone_label': '연락처:',
        'phone_num_text': '0507-1336-1520',
        'email_label': '이메일:',
        'email_address_text': 'ubholic@gmail.com',
        'footer_text': '© 2025 유비홀릭 (UBHOLIC). All Rights Reserved.'
    },
    'en': {
        'site_title': 'UBHOLIC - Beauty Filled with Comfort',
        'logo_text': 'UBHOLIC',
        'nav_language': 'Language',
        'nav_contact': 'Contact',
        'home_title': 'UBHOLIC',
        'home_subtitle': 'Beauty from eyelashes to skin, filled with comfort',
        'branches_title': 'Our Branches',
        'branches_desc': 'Click on a branch to view it on Naver Maps.',
        'branch1_name': 'Jeonju Main Branch',
        'branch1_address': '1F, 16-1 Sotaejeong 3-gil, Wansan-gu, Jeonju-si, Jeollabuk-do',
        'branch1_tel': '0507-1336-1520',
        'branch2_name': 'Iksan Branch',
        'branch2_address': '2F Apple Building, 96 Gungdong-ro, Iksan-si, Jeollabuk-do',
        'branch2_tel': '0507-1390-1189',
        'services_title': 'Main Services',
        'services_desc': 'Discover UBholic\'s professional beauty services.',
        'service1_title': 'Eyelash Extensions',
        'service1_desc': 'Achieve charming eyes with natural and voluminous eyelashes',
        'service2_title': 'Eyelash Perm',
        'service2_desc': 'Maintain stunning curls without an eyelash curler',
        'service3_title': 'Eyelash Restoration',
        'service3_desc': 'Healthy and elastic restoration for damaged eyelashes',
        'service4_title': 'Eyebrows & Eyeline',
        'service4_desc': 'Clear and natural semi-permanent makeup',
        'service5_title': 'Waxing',
        'service5_desc': 'Professional waxing for smooth and clean skin',
        'service6_title': 'Skincare',
        'service6_desc': 'Customized care for healthy and radiant skin',
        'location_title': 'Location (Main Branch)',
        'location_desc': 'UBHOLIC Jeonju Main Branch is located in Hyojadong.',
        'address_label': 'Address:',
        'main_branch_address_text': '1F, 16-1 Sotaejeong 3-gil, Wansan-gu, Jeonju-si, Jeollabuk-do',
        'contact_title': 'Contact Us',
        'contact_desc': 'Please feel free to contact us if you have any questions.',
        'rep_label': 'CEO:',
        'rep_name_text': 'Choi Yubi',
        'phone_label': 'Phone:',
        'phone_num_text': '0507-1336-1520',
        'email_label': 'Email:',
        'email_address_text': 'ubholic@gmail.com',
        'footer_text': '© 2025 UBHOLIC. All Rights Reserved.'
    },
    'vi': { 
        'site_title': 'UBHOLIC - Vẻ đẹp được lấp đầy bởi sự thoải mái',
        'logo_text': 'UBHOLIC',
        'nav_language': 'Ngôn ngữ',
        'nav_contact': 'Liên hệ',
        'home_title': 'UBHOLIC',
        'home_subtitle': 'Vẻ đẹp từ lông mi đến làn da, đong đầy sự thoải mái',
        'branches_title': 'Các chi nhánh',
        'branches_desc': 'Nhấp vào một chi nhánh để xem nó trên Bản đồ Naver.',
        'branch1_name': 'Chi nhánh chính Jeonju',
        'branch1_address': 'Tầng 1, 16-1 Sotaejeong 3-gil, Wansan-gu, Jeonju-si, Jeollabuk-do',
        'branch1_tel': '0507-1336-1520',
        'branch2_name': 'Chi nhánh Iksan',
        'branch2_address': 'Tầng 2 Tòa nhà Apple, 96 Gungdong-ro, Iksan-si, Jeollabuk-do',
        'branch2_tel': '0507-1390-1189',
        'services_title': 'Dịch vụ chính',
        'services_desc': 'Khám phá các dịch vụ làm đẹp chuyên nghiệp của UBholic.',
        'service1_title': 'Nối mi',
        'service1_desc': 'Hoàn thiện đôi mắt cuốn hút với hàng mi tự nhiên và dày dặn',
        'service2_title': 'Uốn mi',
        'service2_desc': 'Duy trì độ cong vút mà không cần kẹp mi',
        'service3_title': 'Phục hồi mi',
        'service3_desc': 'Phục hồi hư tổn cho hàng mi khỏe mạnh và đàn hồi',
        'service4_title': 'Chân mày & Kẻ mắt',
        'service4_desc': 'Trang điểm bán vĩnh viễn rõ nét và tự nhiên',
        'service5_title': 'Waxing',
        'service5_desc': 'Waxing chuyên nghiệp cho làn da mịn màng và sạch sẽ',
        'service6_title': 'Chăm sóc da',
        'service6_desc': 'Chăm sóc tùy chỉnh cho làn da khỏe mạnh và rạng rỡ',
        'location_title': 'Địa điểm (Chi nhánh chính)',
        'location_desc': 'UBHOLIC chi nhánh chính Jeonju tọa lạc tại Hyojadong.',
        'address_label': 'Địa chỉ:',
        'main_branch_address_text': 'Tầng 1, 16-1 Sotaejeong 3-gil, Wansan-gu, Jeonju-si, Jeollabuk-do',
        'contact_title': 'Liên hệ',
        'contact_desc': 'Vui lòng liên hệ nếu bạn có bất kỳ câu hỏi nào.',
        'rep_label': 'Đại diện:',
        'rep_name_text': 'Choi Yubi',
        'phone_label': 'Điện thoại:',
        'phone_num_text': '0507-1336-1520',
        'email_label': 'Email:',
        'email_address_text': 'ubholic@gmail.com',
        'footer_text': '© 2025 UBHOLIC. Đã đăng ký Bản quyền.'
    }
};
