/*
    Last Modified: 2025-07-18 16:01
    Author: Maxim
    Contact: https://www.maxim.pe.kr
    License: © 2025 Maxim. All Rights Reserved.
*/
const languages = {
    // _default: 모든 언어에 공통으로 적용되는 값
    _default: {
        'logo_text': 'UBHOLIC',
        'home_subtitle': 'Premium Esthetic',
        'footer_credit_text': '', // Designed by Maxim 문구 제거
        'location_branch_01_name': '전주본점',
        'location_branch_01_address': '전주시 완산구 소태정3길 16-1',
        'location_branch_01_phone': '0507-1336-1520',
        'location_branch_01_phone_href': 'tel:0507-1336-1520',
        'location_branch_01_url': 'https://naver.me/FvQXWtTY',
        'location_branch_01_services': '피부관리, 속눈썹, 스페셜',
        'location_branch_02_name': '익산점',
        'location_branch_02_address': '익산시 궁동로 96 애플빌딩 2층',
        'location_branch_02_phone': '0507-1390-1189',
        'location_branch_02_phone_href': 'tel:0507-1390-1189',
        'location_branch_02_url': 'https://naver.me/GziC29yG',
        'location_branch_02_services': '두피관리, 속눈썹, 스페셜',
        // --- 서비스(피부관리) ---
        'skincare_card_01_title': '테라피',
        'skincare_card_01_subtitle_01': '얼굴 테라피',
        'skincare_therapy_face_01': '온윤 광채', 'skincare_therapy_face_01_price': '60,000원',
        'skincare_therapy_face_02': '수기 윤결', 'skincare_therapy_face_02_price': '70,000원',
        'skincare_therapy_face_03': '진정 활력', 'skincare_therapy_face_03_price': '60,000원',
        'skincare_therapy_face_04': '청결 균형', 'skincare_therapy_face_04_price': '70,000원',
        'skincare_therapy_face_05': '탄력 채움', 'skincare_therapy_face_05_price': '70,000원',
        'skincare_card_01_subtitle_02': '전신 테라피',
        'skincare_therapy_body_01': '온결 바디', 'skincare_therapy_body_01_price': '180,000원',
        'skincare_therapy_body_02': '선결 탄력', 'skincare_therapy_body_02_price': '90,000원',
        'skincare_therapy_body_03': '균형 회복', 'skincare_therapy_body_03_price': '100,000원',
        'skincare_card_02_title': '집중관리',
        'skincare_intensive_01': '상체', 'skincare_intensive_01_price': '80,000원',
        'skincare_intensive_02': '-- 앞면', 'skincare_intensive_02_price': '40,000원',
        'skincare_intensive_03': '-- 후면', 'skincare_intensive_03_price': '40,000원',
        'skincare_intensive_04': '하체', 'skincare_intensive_04_price': '80,000원',
        'skincare_intensive_05': '-- 앞면', 'skincare_intensive_05_price': '40,000원',
        'skincare_intensive_06': '-- 후면', 'skincare_intensive_06_price': '40,000원',
        'skincare_intensive_07': '복부', 'skincare_intensive_07_price': '40,000원',
        'skincare_intensive_08': '궁', 'skincare_intensive_08_price': '40,000원',
        'skincare_intensive_09': '하지정맥', 'skincare_intensive_09_price': '40,000원',
        'skincare_intensive_10': '겨드랑이 부유방', 'skincare_intensive_10_price': '30,000원',
        'skincare_intensive_11': '지방 흡입 수술 후', 'skincare_intensive_11_price': '80,000원',
        'skincare_intensive_12': '셀룰라이트 집중', 'skincare_intensive_12_price': '40,000원',
        'skincare_card_03_title': '통증관리',
        'skincare_pain_01': '어깨 통증', 'skincare_pain_01_price': '40,000원',
        'skincare_pain_02': '팔꿈치 통증', 'skincare_pain_02_price': '30,000원',
        'skincare_pain_03': '무릎 통증', 'skincare_pain_03_price': '40,000원',
        'skincare_pain_04': '허리 통증', 'skincare_pain_04_price': '40,000원',
        'skincare_pain_05': '고관절', 'skincare_pain_05_price': '40,000원',
        'skincare_pain_06': '상지', 'skincare_pain_06_price': '40,000원',
        'skincare_pain_07': '손', 'skincare_pain_07_price': '30,000원',
        'skincare_pain_08': '발', 'skincare_pain_08_price': '40,000원',
        'skincare_pain_09': '목', 'skincare_pain_09_price': '20,000원',
        'skincare_pain_10': '산후', 'skincare_pain_10_price': '150,000원',
        'skincare_pain_11': '암 수술 후 면역증진', 'skincare_pain_11_price': '60,000원',
        // --- 서비스(속눈썹) ---
        'eyelash_card_01_title': '연장',
        'eyelash_extension_01': '베이직60', 'eyelash_extension_01_price': '35,000원',
        'eyelash_extension_02': '-- 3주이내', 'eyelash_extension_02_price': '30,000원',
        'eyelash_extension_03': '베이직90', 'eyelash_extension_03_price': '45,000원',
        'eyelash_extension_04': '-- 3주이내', 'eyelash_extension_04_price': '40,000원',
        'eyelash_extension_05': '유비래쉬', 'eyelash_extension_05_price': '50,000원',
        'eyelash_extension_06': '-- 3주이내', 'eyelash_extension_06_price': '30,000원',
        'eyelash_extension_07': '리얼래쉬', 'eyelash_extension_07_price': '60,000원',
        'eyelash_extension_08': '-- 3주이내', 'eyelash_extension_08_price': '40,000원',
        'eyelash_extension_09': '유비 블랙 R3', 'eyelash_extension_09_price': '65,000원',
        'eyelash_card_02_title': '펌',
        'eyelash_perm_01': '베이직펌', 'eyelash_perm_01_price': '25,000원',
        'eyelash_perm_02': '-- 5주이내', 'eyelash_perm_02_price': '20,000원',
        'eyelash_perm_03': '프로틴펌', 'eyelash_perm_03_price': '35,000원',
        'eyelash_perm_04': '-- 5주이내', 'eyelash_perm_04_price': '30,000원',
        'eyelash_perm_05': '케라틴펌', 'eyelash_perm_05_price': '50,000원',
        'eyelash_perm_06': '-- 5주이내', 'eyelash_perm_06_price': '40,000원',
        'eyelash_perm_07': '에딕트컬펌', 'eyelash_perm_07_price': '60,000원',
        'eyelash_perm_08': '-- 5주이내', 'eyelash_perm_08_price': '50,000원',
        'eyelash_card_03_title': '복원',
        'eyelash_restore_01': '1회', 'eyelash_restore_01_price': '110,000원',
        'eyelash_restore_02': '3회', 'eyelash_restore_02_price': '330,000원',
        'eyelash_restore_03': '5회', 'eyelash_restore_03_price': '450,000원',
        'eyelash_restore_04': '10회', 'eyelash_restore_04_price': '660,000원',
        // --- 서비스(스페셜) ---
        'special_card_01_title': '자연눈썹', 'special_card_01_price': '180,000원',
        'special_card_02_title': '화장눈썹', 'special_card_02_price': '200,000원',
        'special_card_03_title': '아이라인', 'special_card_03_price': '150,000원',
        'special_card_04_title': '미인점', 'special_card_04_price': '30,000원',
    },
    // 영어 언어 팩
    'en': {
        'site_title': 'UBHOLIC - Premium Esthetic',
        'overview_title': 'Comfort and Beauty that Permeates Your Daily Life',
        'overview_desc': 'UBHOLIC is a premium esthetic that provides true rest and vitality to your body and mind with professional care tailored to each customer.',
        'skincare_title': 'Skincare',
        'skincare_desc': 'Rediscover your skin\'s natural glow with our expert touch.',
        'eyelash_title': 'Eyelash',
        'eyelash_desc': 'We delicately design your eyes, one lash at a time.',
        'special_title': 'Special Care',
        'special_desc': 'Boost your confidence with our special care services.',
        'special_card_01_desc': 'We design the most natural-looking eyebrow texture to fit your individual face shape.',
        'special_card_02_desc': 'Creates a clear impression with natural shading, as if wearing makeup.',
        'special_card_03_desc': 'Meticulously fills the waterline for defined and deep eyes, even without makeup.',
        'special_card_04_desc': 'Adds a unique personality by creating a charming beauty mark in the desired location.',
        'location_title': 'Our Branches',
        'location_desc': 'Experience the best care at your nearest UBHOLIC.',
        'location_label_address': 'Address:',
        'location_label_phone': 'Phone:',
        'location_label_services': 'Services:',
        'location_button_text': 'View on Map',
    },
    // 한국어 언어 팩
    'ko': {
        'site_title': '유비홀릭 - 프리미엄 에스테틱',
        'overview_title': '일상에 스며드는 편안함과 아름다움',
        'overview_desc': '유비홀릭은 고객 한 분 한 분에게 맞춘 전문적인 케어로 몸과 마음에 진정한 휴식과 활력을 선사하는 프리미엄 에스테틱입니다.',
        'skincare_title': '피부관리',
        'skincare_desc': '전문가의 손길로 피부 본연의 건강한 빛을 되찾아 드립니다.',
        'eyelash_title': '속눈썹',
        'eyelash_desc': '한 올 한 올 섬세한 터치로 당신의 눈매를 가장 아름답게 디자인합니다.',
        'special_title': '스페셜 케어',
        'special_desc': '당신의 숨겨진 매력을 찾아 자신감을 더해주는 특별한 관리입니다.',
        'special_card_01_desc': '개개인의 얼굴형에 맞춰 가장 자연스러운 눈썹 결을 디자인합니다.',
        'special_card_02_desc': '화장한 듯 자연스러운 음영을 주어 또렷한 인상을 완성합니다.',
        'special_card_03_desc': '점막을 꼼꼼히 채워 민낯에도 선명하고 깊은 눈매를 연출합니다.',
        'special_card_04_desc': '원하는 위치에 매력 포인트를 만들어 특별한 개성을 더합니다.',
        'location_title': '지점 안내',
        'location_desc': '가까운 유비홀릭에서 최상의 케어를 경험해 보세요.',
        'location_label_address': '주소:',
        'location_label_phone': '연락처:',
        'location_label_services': '서비스:',
        'location_button_text': '지도에서 보기',
    }
};
